=== Hagleitner-Business-Applications/hagleitner-bdim/v0.1/model/interactionLogEntry/interactionLogEntry.schema.json
{
    "$id": "interactionLogEntry.schema.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "x-revision": "2026-06-07",
    "type": "object",
    "unevaluatedProperties": false,
    "required": [
        "id",
        "customerId",
        "contactId",
        "entryNo",
        "date",
        "description",
        "salespersonId",
        "userId",
        "interactionGroup",
        "interactionTemplate",
        "campaignNo",
        "campaignDescription",
        "segmentNo",
        "segmentDescription",
        "documentType",
        "documentNo",
        "documentversionNo",
        "fileattachmentLink",
        "fileattachmentBase64"
    ],
    "properties": {
        "id": {
            "$ref": "../components/basetypes.schema.json#/$defs/uuid",
            "description": "The unique identifier for the interactionLogEntry.",
            "x-status": "draft"
        },
        "customerId": {
            "$ref": "../components/basetypes.schema.json#/$defs/uuid",
            "description": "The unique identifier for the customer.",
            "x-status": "draft"
        },
        "contactId": {
            "$ref": "../components/basetypes.schema.json#/$defs/uuid",
            "description": "The unique identifier for the contact.",
            "x-status": "draft"
        },
        "entryNo": {
            "$ref": "../components/basetypes.schema.json#/$defs/code",
            "maxLength": 20,
            "description": "The unique entry number for the interaction log entry.",
            "x-status": "draft"
        },
        "date": {
            "type": "string",
            "format": "date-time",
            "description": "RFC 3339 date-time when the interactionLogEntry was first created in the owning system.",
            "x-status": "draft"
        },
        "description": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "maxLength": 100,
            "description": "A detailed description of the interaction log entry.",
            "x-status": "draft"
        },
        "salespersonId": {
            "$ref": "../components/basetypes.schema.json#/$defs/uuid",
            "description": "The unique identifier for the salesperson associated with the interaction log entry.",
            "x-status": "draft"
        },
        "userId": {
            "$ref": "../components/basetypes.schema.json#/$defs/uuid",
            "description": "The unique identifier for the user who created the interaction log entry.",
            "x-status": "draft"
        },
        "interactionGroup": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "maxLength": 100,
            "description": "The code representing the interaction group.",
            "x-status": "draft"
        },
        "interactionTemplate": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "maxLength": 100,
            "description": "The code representing the interaction template.",
            "x-status": "draft"
        },
        "campaignNo": {
            "$ref": "../components/basetypes.schema.json#/$defs/code",
            "maxLength": 20,
            "description": "The unique campaign number associated with the interaction log entry.",
            "x-status": "draft"
        },
        "campaignDescription": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "maxLength": 100,
            "description": "A brief description of the campaign associated with the interaction log entry.",
            "x-status": "draft"
        },
        "segmentNo": {
            "$ref": "../components/basetypes.schema.json#/$defs/code",
            "maxLength": 20,
            "description": "The unique segment number associated with the interaction log entry.",
            "x-status": "draft"
        },
        "segmentDescription": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "maxLength": 100,
            "description": "A brief description of the segment associated with the interaction log entry.",
            "x-status": "draft"
        },
        "documentType": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "maxLength": 50,
            "description": "The code representing the document type associated with the interaction log entry.",
            "x-status": "draft"
        },
        "documentNo": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "maxLength": 20,
            "description": "The unique document number associated with the interaction log entry.",
            "x-status": "draft"
        },
        "documentversionNo": {
            "type": "integer",
            "minimum": 0,
            "maxLength": 20,
            "description": "The unique document version number associated with the interaction log entry.",
            "x-status": "draft"
        },
        "fileattachmentLink": {
            "$ref": "../components/basetypes.schema.json#/$defs/singleLineText",
            "format": "uri",
            "maxLength": 200,
            "description": "A link to the file attachment associated with the interaction log entry.",
            "x-status": "draft"
        },
        "fileattachmentBase64": {
            "$ref": "../components/basetypes.schema.json#/$defs/base64",
            "description": "The base64 encoded content of the file attachment associated with the interaction log entry.",
            "x-status": "draft"
        }

    }
}

=== Hagleitner-Business-Applications/hagleitner-bdim/v0.1/model/interactionLogEntry/interactionLogEntry.example.json
{
"id": "123465dd-b951-4806-a9e2-85dd5a0e5949",
"customerId": "8f8665dd-b951-4806-a9e2-85dd5a0e5949",
"contactId": "8f8665dd-b951-4806-a9e2-85dd5a0e5949",
"entryNo": "1231236",
"date": "2023-08-01T10:00:00Z",
"description": "Reinigungsplan gedruckt",
"salespersonId": "8f8665dd-b951-4806-a9e2-85dd5a0e5949",
"userId": "8f8665dd-b951-4806-a9e2-85dd5a0e5949",
"interactionGroup": "Dosiertechnik",
"interactionTemplate": "Reinigungsplan", 
"campaignNo": "KA00012",   
"campaignDescription": "Beherbergungsgastronomie",
"segmentNo": "SEG000123",
"segmentDescription": "Segmentierung Beherbergung",
"documentType": "Reinigungsplan",
"documentNo": "HAD_145900029",
"documentversionNo": 1,
"fileattachmentLink": "https://sharepoint.hagleitner.com/sites/BDIM/Shared%20Documents/InteractionLogEntry/HAD_145900029.pdf",
"fileattachmentBase64": "JVBERi0xLjQKJcfsj6IKNSAwIG9iago8PC9UeXBlL1BhZ2UvUGFyZW50IDQgMCBSL1Jlc291cmNlcyA2IDAgUi9NZWRpYUJveFswIDAgNjEyIDc5Ml0vQ29udGVudHMgNyAwIFI+PgplbmRvYmoKNiAwIG9iago8PC9Qcm9jU2V0Wy9QREZdL0ZvbnQgOCAwIFJdPj4KZW5kb2JqCjcgMCBvYmoKPDwvTGVuZ3RoIDg1Pj4Kc3RyZWFtCnic7V1NT9swELz7K5k6aWlq6pS0tLQkq"
}
